import type { NextPage } from 'next'
import React, { useState } from "react"
import { useRouter } from "next/router";
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SearchInput from '../components/SearchInput'

const Home: NextPage = () => {
  const [ownerKey, setOwnerKey] = useState("");
  const router = useRouter();
  
  const goView = () => {
    router.push("/view");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <span className='text-6xl mb-16 font-bold'> NFT Viewer </span>
        <SearchInput className='flex flex-row w-1/2 items-center justify-center' text={ownerKey} onChangeHandler={setOwnerKey}  onClickHandler={goView}></SearchInput>
      </main>
    </div>
  )
}

export default Home
